#server:
#  port: 80

spring:
  application:
    name: hubing

  profiles:
    active: dev # 默认为开发环境

  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 300MB #限制文件上传大小为300M
      max-request-size: 300MB

  redis:
    port: 6379
    database: 0
    host: 127.0.0.1
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 5000ms

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

scheduled:
  cron: 0 0 0 * * ? #每天凌晨执行定时任务
  hour: 1 #每小时执行一次定时任务
  minute: 1 #每分钟执行一次定时任务
  second: 1 #每秒执行一次定时任务
  hourAndMinute: 1:1 #每天1点1分执行一次定时任务
  minute10: 0 0/10 * * * ? #每10分钟执行一次定时任务
  fixedRate: 1000 #每隔1秒执行一次定时任务
  fixedDelay: 1000 #每隔1秒执行一次定时任务
  initialDelay: 1000 #延迟1秒后执行定时任务


#jwt:
#  tokenHeader: Authorization #JWT存储的请求头
#  secret: mall-admin-secret #JWT加解密使用的密钥
#  expiration: 604800 #JWT的超期限时间(60*60*24*7)
#  tokenHead: 'Bearer '  #JWT负载中拿到开头